// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ckEpPjsfMwn_XTJmUQKiRl1P9GpJBOE',
    appId: '1:205095642995:web:b1a7ae743b440e2ed48706',
    messagingSenderId: '205095642995',
    projectId: 'amanghar-app',
    authDomain: 'amanghar-app.firebaseapp.com',
    storageBucket: 'amanghar-app.firebasestorage.app',
    measurementId: 'G-7Z0C3PQ0HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-3BkFjcv_ibtiK7jaRF23iOmW0Uo-6NQ',
    appId: '1:205095642995:android:0938011733351eb8d48706',
    messagingSenderId: '205095642995',
    projectId: 'amanghar-app',
    storageBucket: 'amanghar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMiFETL4JAygCLD7NWyHJLhv5BkAv1mBg',
    appId: '1:205095642995:ios:bcf7fed1630471f6d48706',
    messagingSenderId: '205095642995',
    projectId: 'amanghar-app',
    storageBucket: 'amanghar-app.firebasestorage.app',
    iosBundleId: 'com.example.amangharApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMiFETL4JAygCLD7NWyHJLhv5BkAv1mBg',
    appId: '1:205095642995:ios:bcf7fed1630471f6d48706',
    messagingSenderId: '205095642995',
    projectId: 'amanghar-app',
    storageBucket: 'amanghar-app.firebasestorage.app',
    iosBundleId: 'com.example.amangharApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ckEpPjsfMwn_XTJmUQKiRl1P9GpJBOE',
    appId: '1:205095642995:web:fd6e284cf91725ead48706',
    messagingSenderId: '205095642995',
    projectId: 'amanghar-app',
    authDomain: 'amanghar-app.firebaseapp.com',
    storageBucket: 'amanghar-app.firebasestorage.app',
    measurementId: 'G-TX5CQ5R07H',
  );

}